<?php
/**
 * Nifty - A WordPress theme development framework.
 *
 * This functions file is used for initializing the theme framework, witch activates
 * files in the order that needs.
 * 
 * Users should create a child theme and make changes to its functions.php file.
 *
 * TODO: DO NOT edit this file under any circumstances.
 *
 * @package Nifty
 * @subpackage Functions
 */

/* Load the Nifty Theme Framework. */
require_once( get_template_directory() . '/library/nifty.php' );
